version: '3'

networks:
    app:

services:
    redis_slave:
        image: redis:5-alpine
        logging:
          options:
            max-size: "10m"
            max-file: "3"
        ports: [6379]
        sysctls:
          net.core.somaxconn: 16384
        ulimits:
          nproc: 65535
          nofile:
            soft: 65535
            hard: 65535
        command: redis-server --slaveof rtbadmin.vidoomy.com 32798
        networks:
          - app

    php:
        build:
          context: .
          dockerfile: docker/php/Dockerfile
        restart: on-failure
        dns:
           - 8.8.8.8
           - 8.8.4.4
        logging:
          options:
            max-size: "10m"
            max-file: "3"
        env_file:
          - .env
        sysctls:
          net.core.somaxconn: 16384
        ulimits:
          nproc: 65535
          nofile:
            soft: 65535
            hard: 65535
        depends_on:
          - redis_slave
        networks:
          - app

    nginx:
        build:
          context: .
          dockerfile: docker/nginx/Dockerfile
        logging:
          options:
            max-size: "10m"
            max-file: "3"
        restart: on-failure
        depends_on:
          - php
        volumes:
          - './public/:/usr/src/app'
          - './docker/nginx/conf.d:/etc/nginx/conf.d:ro'
          - './docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro'
          - './docker/nginx/mime.type:/etc/nginx/mime.type:ro'
          - './docker/nginx/upstream.d:/etc/nginx/upstream.d:ro'
          - './data/certs:/etc/nginx/certs'
        ulimits:
          nproc: 65535
          nofile:
            soft: 65535
            hard: 65535
        sysctls:
          net.core.somaxconn: 16384
        ports:
          - '90:80'
          - '443:443'
        networks:
          - app