<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4K4bHtC\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4K4bHtC/App_KernelProdContainer.php') {
    touch(__DIR__.'/Container4K4bHtC.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\Container4K4bHtC\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \Container4K4bHtC\App_KernelProdContainer([
    'container.build_hash' => '4K4bHtC',
    'container.build_id' => '27a10abf',
    'container.build_time' => 1595598302,
], __DIR__.\DIRECTORY_SEPARATOR.'Container4K4bHtC');
