<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'ad_printed' => [[], ['_controller' => 'App\\Controller\\AdPrintedController::index'], [], [['text', '/show/']], [], []],
    'ad_request' => [[], ['_controller' => 'App\\Controller\\AdRequestController::index'], [], [['text', '/']], [], []],
    'cookie_sync' => [[], ['_controller' => 'App\\Controller\\CookieSyncController::index'], [], [['text', '/cookie/']], [], []],
];
